[mgr]
prepend_keymap = [
	{ on = "<S-Up>",   run = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = "<S-Down>", run = "arrow 5",  desc = "Move cursor down 5 lines" },
	{ on = "~",        run = "cd ~",     desc = "Go to home directory" },
	{ on = "<C-Up>",    run = "arrow -99999999", desc = "Go to top" },
	{ on = "<C-Down>",  run = "arrow 99999999",  desc = "Go to bottom" },
	{ on = "<C-f>",         run = "plugin jump-to-char", desc = "Jump to char" },
	{ on = "<Enter>",   run = "plugin smart-enter", desc = "Open file or enter directory" },
	{ on = "f",     run = "filter --smart",     desc = "Filter files" },
	{ on = "<A-Up>",    run = "seek -5",  desc = "Scroll preview up" },
	{ on = "<A-Down>",  run = "seek 5",   desc = "Scroll preview down" },
	{ on = "q",         run = "quit",     desc = "Quit and cd to current directory" },
	{ on = "Q",         run = "quit --no-cwd-file", desc = "Quit without changing directory" },
]
