[mgr]
prepend_keymap = [
	{ on = "<S-Up>",   run = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = "<S-Down>", run = "arrow 5",  desc = "Move cursor down 5 lines" },
	{ on = "~",        run = "cd ~",     desc = "Go to home directory" },
	{ on = "<C-Up>",    run = "seek -5",  desc = "Scroll preview up" },
	{ on = "<C-Down>",  run = "seek 5",   desc = "Scroll preview down" },
]
