[mgr]
prepend_keymap = [
	{ on = "<C-Up>",   run = "arrow -5", desc = "Move cursor up 5 lines" },
	{ on = "<C-Down>", run = "arrow 5",  desc = "Move cursor down 5 lines" },
	{ on = "~",        run = "cd ~",     desc = "Go to home directory" },
]
